# Generated by Django 6.0.3 on 2026-03-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vat_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CIF/NIF'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección Fiscal/Física'),
        ),
        migrations.AlterField(
            model_name='user',
            name='certifications',
            field=models.TextField(blank=True, help_text='Certificaciones de calidad y cumplimiento sanitario (ISO 13485, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de la Empresa'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de contacto'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('clinic', 'Clínica Dental'), ('lab', 'Laboratorio de Prótesis')], default='clinic', help_text='Rol que define los permisos y la interfaz del usuario en la plataforma', max_length=20),
        ),
    ]
