# Generated by Django 6.0.3 on 2026-04-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_vat_id_alter_user_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='consultation_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio orientativo de consulta para comparador de clínicas', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valoración media de la clínica (0.00 - 5.00)', max_digits=3, null=True),
        ),
    ]
