[setup]
nixPkgs = ["python3", "postgresql_16.dev", "gcc", "nodejs_22"]

[install]
cmds = [
  "python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt",
  "npm install --prefix frontend --legacy-peer-deps"
]

[build]
cmds = [
  ". /opt/venv/bin/activate && npm run build --prefix frontend",
  "python manage.py collectstatic --noinput",
  "python manage.py migrate"
]

[start]
cmd = ". /opt/venv/bin/activate && gunicorn talento360.wsgi:application --log-file -"
