# Generated by Django 6.0.3 on 2026-03-17 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('external_id', models.CharField(blank=True, help_text='ID interno de la clínica', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(limit_choices_to={'role': 'clinic'}, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('fixed', 'Prótesis Fija'), ('removable', 'Prótesis Removible'), ('implant', 'Implantoprótesis'), ('ortho', 'Ortodoncia'), ('other', 'Otros')], default='fixed', max_length=20)),
                ('material', models.CharField(help_text='Ej: Circonio, Disilicato, Cobalto-Cromo', max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_days', models.IntegerField(default=5, help_text='Días laborables estimados')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='marketplace.category')),
                ('lab', models.ForeignKey(limit_choices_to={'role': 'lab'}, on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('received', 'Recibido en Laboratorio'), ('design', 'En Diseño Digital'), ('production', 'En Producción/Fresado'), ('finishing', 'Acabado y Cerámica'), ('quality', 'Control de Calidad'), ('shipped', 'Enviado'), ('completed', 'Finalizado en Clínica'), ('cancelled', 'Cancelado')], default='received', max_length=20)),
                ('teeth_numbers', models.CharField(help_text='Ej: 11, 12, 46 (FDI notation)', max_length=100)),
                ('shade', models.CharField(blank=True, help_text='Color (VITA, Ivoclar)', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Instrucciones clínicas')),
                ('scan_url', models.URLField(blank=True, help_text='Link al escaneado intraoral (.STL)', null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(limit_choices_to={'role': 'clinic'}, on_delete=django.db.models.deletion.CASCADE, related_name='orders_placed', to=settings.AUTH_USER_MODEL)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_received', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='marketplace.patient')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.product')),
            ],
        ),
    ]
