# Generated by Django 6.0.3 on 2026-03-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='external_source',
            field=models.CharField(blank=True, help_text='Ej: Shopify, WooCommerce, Personal', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='external_url',
            field=models.URLField(blank=True, help_text='Link directo al producto en la tienda original del laboratorio', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_external',
            field=models.BooleanField(default=False, help_text='Indica si el producto fue sincronizado desde una tienda externa'),
        ),
    ]
