# Generated by Hand on 2026-03-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_product_external_source_product_external_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='design_url',
            field=models.URLField(blank=True, help_text='Link al diseño propuesto por el laboratorio (.STL)', null=True),
        ),
    ]
