# Generated by Django 6.0.3 on 2026-03-27 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_order_design_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='external_source',
        ),
        migrations.AddField(
            model_name='order',
            name='priority',
            field=models.BooleanField(default=False, verbose_name='Pedido Urgente'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre de la Categoría'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Nombre amigable para la URL (ej: protesis-fija)', unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='design_url',
            field=models.URLField(blank=True, help_text='Link al diseño propuesto para validación', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de entrega pactada'),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, help_text='Instrucciones clínicas detalladas'),
        ),
        migrations.AlterField(
            model_name='order',
            name='scan_url',
            field=models.URLField(blank=True, help_text='Link al archivo .STL del escaneado inicial', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shade',
            field=models.CharField(blank=True, help_text='Color dental (Guía VITA, Ivoclar, etc.)', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='teeth_numbers',
            field=models.CharField(help_text='Piezas dentales (ej: 11, 12, 46) usando notación FDI', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='external_id',
            field=models.CharField(blank=True, help_text='ID interno de la clínica (historia clínica)', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='product',
            name='delivery_days',
            field=models.IntegerField(default=5, help_text='Días laborables estimados de fabricación'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Descripción Técnica'),
        ),
        migrations.AlterField(
            model_name='product',
            name='external_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL Tienda Original'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Imagen de muestra'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_external',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre del Servicio'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio base'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_url', models.URLField(blank=True, help_text='Link al archivo .PDF de la factura', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='Número de Factura')),
                ('client_info', models.TextField(help_text='Datos fiscales de la clínica (Snapshot)')),
                ('lab_info', models.TextField(help_text='Datos fiscales del laboratorio (Snapshot)')),
                ('product_name', models.CharField(help_text='Nombre del producto en el momento de facturar', max_length=255)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=21.0, help_text='IVA aplicado (%)', max_digits=5)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagada')], default='pending', max_length=20)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('qr_code', models.ImageField(blank=True, help_text='QR de trazabilidad para la caja física', null=True, upload_to='invoices/qr/')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='marketplace.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Fotos del paciente o referencias de color', upload_to='orders/photos/')),
                ('description', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='marketplace.order')),
            ],
        ),
    ]
