# Generated by Django 6.0.3 on 2026-04-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_orderevent_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='messages/images/'),
        ),
    ]
