# Generated by Django 6.0.3 on 2026-04-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_ordermessage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermessage',
            name='content',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
    ]
