# Generated by Django 6.0.3 on 2026-04-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_alter_ordermessage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assigned_technician',
            field=models.CharField(blank=True, help_text='Técnico responsable del caso dentro del laboratorio', max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='production_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
